version: '3.7'

services:
  client:
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--max-old-space-size=4096
      - REACT_APP_SERVER_URL=http://localhost:7070
    ports:
      - '3000:3000'
    command: yarn start
    volumes:
      - ./client:/app
      - /app/node_modules
    container_name: client
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - BOT_URL=http://localhost:6060
      - PORT=7070
    ports:
      - '7070:7070'
    command: yarn start
    volumes:
      - ./server:/app/
      - /app/node_modules
    container_name: server
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - PORT=6060
    ports:
      - '6060:6060'
    command: yarn start
    volumes:
      - ./bot:/app/
      - /app/node_modules
    container_name: bot